config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

gig_finder_admin/urls.py
from django.urls import  path, include
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'gigFinderAdmin'
urlpatterns = [
    path('home/', views.home_view, name='homeIndex'),
    path('users/', login_required(views.UserIndexView.as_view()), name='userIndex'),    
    path('jobs/', login_required(views.JobIndexView.as_view()), name='jobIndex'),
    path('<str:model>/download/', views.export, name='modelExport')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('gigFinder/', include('gig_finder_admin.urls', namespace='gigFinder')),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

polls/urls.py
from django.urls import  path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:pk>/vote/', views.vote, name='vote')
]

gig_finder_admin/models.py
from django.db import models

class Job(models.Model):
	title = models.CharField(max_length=250, default='')
	link = models.CharField(max_length=250, default='')
	category = models.CharField(max_length=250, default='')

class Ints(models.Model):
	ints1 = models.CharField(max_length=250, default='')
	ints2 = models.CharField(max_length=250, default='')

class User(models.Model):
	FirstName = models.CharField(max_length=250, default='')
	LastName = models.CharField(max_length=250, default='')
	Email = models.CharField(max_length=250, default='')
	interest1 = models.CharField(max_length=250, default='')
	interest2 = models.CharField(max_length=250, default='')

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return timezone.now() - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

gig_finder_admin/views.py
import csv

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse, HttpResponseRedirect, StreamingHttpResponse
from django.shortcuts import render, get_list_or_404, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .resources import UserResource, JobResource
from .models import Job, User, Ints

# Create your views here.
class UserIndexView(generic.ListView):
    template_name = 'user/index.html'
    context_object_name = 'users'
    model = User
    paginate_by = 10
   
class JobIndexView(generic.ListView):
    template_name = 'job/index.html'
    context_object_name = 'jobs'
    model = Job
    paginate_by = 10

@login_required
def home_view(request):
    return render(request, 'home/index.html')

# Streaming csv file
@login_required
def export(request, model):
    if model == 'users':
        resource = UserResource()
    elif model == 'jobs':
        resource = JobResource()
    else: return None

    dataset = resource.export()
    response = HttpResponse(dataset.csv, content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="{}.csv"'.format(model)
    return response

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latestQuestions'

    def get_queryset(self):
        '''
        Overrides get_queryset from generic.ListView to implement custom lookup logic.
        '''
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, pk):
    question = get_object_or_404(Question, pk=pk)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

gig_finder_admin/templates/authentication/login.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static './css/gigFinder.css' %}">
{% endblock %}

{% block content %}
<form action="{% url 'gigFinder:login' %}" method="POST">
    {% csrf_token %}
    <div class="text-center mb-4">
        <h1 class="h3 mb-3 font-weight-normal">Log In</h1>
    </div>

    {% if error_message %}
        <p style="color: red">
            <strong>Your username or password didn't match. Please try again.</strong>
        </p>
    {% endif %}

    <div class="form-group">
        <label for="username">Username</label>
        <input type="text" id="username" name="username" class="form-control"> 
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" id="password" name="password" class="form-control"> 
    </div>
    <button class="btn btn-primary btn-block">Submit</button>
</form>
{% endblock %}

gig_finder_admin/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
    <p>It works!</p>
{% endblock %}

gig_finder_admin/templates/job/index.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static './css/gigFinder.css' %}">
{% endblock %}

{% block content %}

  <div class="row">
    <div class="col-6">
      <h3>Registered Jobs</h3>
    </div>   
  </div>
  <div class="row">
    <div class="col-6">
        <h6 class="mb-2 text-muted">List of all registered jobs on Gig Finder</h6>
    </div>
    <div class="offset-3 col-3">
      <input type="hidden" id="modelUrl" value="{{ request.get_host }}{% url 'gigFinder:modelExport' 'jobs'%}">
      <button type="button" class="btn btn-block btn-primary" onclick="exportModel('modelUrl')">Download List</button>
    </div>   
  </div>

  <br>

  {% if jobs %}

  {% include "paginator.html" %}
    <div class="row">
      <div class="col-12">
          <table class="table table-hover">
              <thead class="thead-dark">
                <tr>
                  <th class="w-25" scope="col">#</th>
                  <th class="w-25" scope="col">Title</th>
                  <th class="w-25" scope="col">Category</th>
                  <th class="w-50" scope="col">Link</th>  
                </tr>
              </thead>
              <tbody>
                {% for job in jobs %}
                  <tr>
                    <th scope="row">{{ job.id }}</th>
                    <td class="w-25">{{ job.title }}</td>
                    <td class="w-25">{{ job.category }}</td>
                    <td class="w-50">
                      <a href="{{ job.link }}" target="_blank" class="btn btn-secondary">Go to webpage</a>      
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
      </div>
    </div>
  {% include "paginator.html" %}    
  
{% endif %}

{% endblock %}

{% block scripts %}
  <script src="{% static 'js/util.js' %}"></script>
{% endblock %}

gig_finder_admin/templates/user/index.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static './css/gigFinder.css' %}">
{% endblock %}

{% block content %}

  <div class="row">
    <div class="col-6">
      <h3>Registered Users</h3>
    </div>   
  </div>
  <div class="row">
    <div class="col-6">
        <h6 class="mb-2 text-muted">List of all registered users on Gig Finder</h6>
    </div>
    <div class="offset-3 col-3">
      <input type="hidden" id="modelUrl" value="{{ request.get_host }}{% url 'gigFinder:modelExport' 'users'%}">
      <button type="button" class="btn btn-block btn-primary" onclick="exportModel('modelUrl')">Download List</button>
    </div>   
  </div>

  <br>

  {% if users %}

    {% include "paginator.html" %}
    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Email</th>
          <th scope="col">Interest #1</th>
          <th scope="col">Interest #2</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <th scope="row">{{ user.id }}</th>
            <td>{{ user.FirstName }}</td>
            <td>{{ user.LastName }}</td>
            <td>{{ user.Email }}</td>
            <td>{{ user.interest1 }}</td>
            <td>{{ user.interest2 }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% include "paginator.html" %}    
    
  {% endif %}

{% endblock %}

{% block scripts %}
  <script src="{% static 'js/util.js' %}"></script>
{% endblock %}

polls/templates/polls/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ question.question_text }}</h1>

{% if error_message %}
    <p><strong>
        {{ error_message }}
    </strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="POST">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" 
            name="choice" 
            id="choice{{forloop.counter}}"
            value="{{ choice.id }}">
        <label for="choice{{forloop.counter}}">{{ choice.choice_text }}</label>
        <br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>
{% endblock %}

polls/templates/polls/index.html
{% extends 'base.html' %}

{% block content %}
    {% if latestQuestions %}
        <ul>
            {% for question in latestQuestions %}
                <li>
                    <a href="{% url 'polls:detail' question.id %}">
                            {{ question.question_text }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>
            {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
        </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
      <meta charset="utf-8">
      <title>{% block title %}Gig Finder Admin{% endblock %}</title>
      <link rel="stylesheet" href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/app.css' %}">
      {% block stylesheet %}{% endblock %}
    </head>
    <body>
      {% block body %}

      {% include "navbar.html" %}

      <div class="container body-pad25">
        {% block content %}
        {% endblock %}
      </div>

      <script src="{% static 'libs/jquery/jquery-3.3.1.min.js' %}"></script>
      <script src="{% static 'libs/bootstrap/js/bootstrap.min.js' %}"></script>
      {% block scripts %}{% endblock %}

      {% endblock body %}
    </body>
</html>

templates/navbar.html
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'polls:index' %}">Gig Finder Admin</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'gigFinder:userIndex' %}">Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'gigFinder:jobIndex' %}">Jobs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Log out</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
        <span class="navbar-text">Welcome back, <strong>{{ user.username }}</strong></span>
      {% endif %}
    </div>    
</nav>
{% endblock %}

templates/paginator.html
{% if is_paginated %}
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        {% endif %}
        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-item active"><span class="page-link">{{ i }}<span class="sr-only">(current)</span></span></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% else %}
        <li class="page-item disabled"><span class="page-link">Next</span></li>
        {% endif %}
    </ul>
{% endif %}